### ISSUE TITLE
How to setText : loading...  in bottom dialog ?

### ISSUE THREAD

**Issue by dogialong** [Rogero0o/CatLoadingView#10]
Please help me !

**Comment by Rogero0o** [comment]
You can add an method in CatLoadingView.java to do this. The textview named mGraduallyTextView , you can use mGraduallyTextView.setText("..."); to get what you want. Thank you for asking.

**Comment by dogialong** [comment]
thank you for answ .But it still not working . Here my code : 

  mView = new CatLoadingView();
        GraduallyTextView mGraduallyTextView = new GraduallyTextView(getApplicationContext());
        mGraduallyTextView.setText("Loading...");
        findViewById(R.id.button).setOnClickListener(
                new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        mView.show(getSupportFragmentManager(), "");
                    }
                });

**Comment by Rogero0o** [comment]
You should download my project and change CatLoadingView.java in com.roger.catloadinglibrary ..
Add an method to do this . 
If you still confuse about that , wait for me to change it for you this night . 
Thanks~
