### ISSUE TITLE
Sorry but i can't do display text : Loading ...

### ISSUE THREAD

**Issue by dogialong** [Rogero0o/CatLoadingView#11]
thank you for answ .But it still not working . Here my code :

mView = new CatLoadingView();
GraduallyTextView mGraduallyTextView = new GraduallyTextView(getApplicationContext());
mGraduallyTextView.setText("Loading...");
findViewById(R.id.button).setOnClickListener(
new View.OnClickListener() {
@Override
public void onClick(View v) {
mView.show(getSupportFragmentManager(), "");
}
});

**Comment by Rogero0o** [comment]
I have added an method called setText in CatLoadingView . Check it out , it can help you.
