### ISSUE TITLE
超喜欢你的设计，但是有些bug

### ISSUE THREAD

**Issue by cyan333** [Rogero0o/CatLoadingView#15]
在nexus的机子上run都没有问题，可是在非google手机上，like 华为，run的时候，loading的下半部分被遮住了！ToT！
有的时候眼睛，eyelipview与猫脸的背景没有对齐，导致眼珠转到了外面！
希望对你改进这个设计有帮助！！

实在太喜欢这个设计了！谢谢。

**Comment by Rogero0o** [comment]
谢谢~很高兴你能喜欢，下一步将着手处理适配的问题
