### ISSUE TITLE
change loading message 

### ISSUE THREAD

**Issue by seungyeop-shin** [Rogero0o/CatLoadingView#16]
not work

**Comment by Rogero0o** [comment]
What do you mean not work ? Please show me the code .

**Comment by seungyeop-shin** [comment]
i want change loading message . but CatLoadingView is cannot resolve method setText()

compile 'com.roger.catloadinglibrary:catloadinglibrary:1.0.1'

**Comment by Rogero0o** [comment]
Please change to 'com.roger.catloadinglibrary:catloadinglibrary:1.0.2' . 
I just updated it .
Thanks.

**Comment by seungyeop-shin** [comment]
good job!! 
minsdkversion 14 cannot be smaller than version 19 declared in library
compile 'com.roger.catloadinglibrary:catloadinglibrary:1.0.1' = version 14
compile 'com.roger.catloadinglibrary:catloadinglibrary:1.0.2' =  version 19
sorry but, i want 14 version!!

**Comment by Rogero0o** [comment]
Sorry about that~
I just uploaded 1.0.3 which the minsdkversion is 14 .
Please check it later. Thanks.

**Comment by seungyeop-shin** [comment]
I'm sorry to bother you.
Thanks. ^^
