### ISSUE TITLE
Null pointer Exception in mView.dismiss() after configuration changes 

### ISSUE THREAD

**Issue by gautam2682** [Rogero0o/CatLoadingView#20]
I am getting -

`      java.lang.NullPointerException: Attempt to invoke virtual method android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference
`
when i rotate the phone and it crashes becuase of mView.dismiss(). Please help.)

**Comment by ponnamkarthik** [comment]
wrap your code in 

```java
if(mView != null) {
    mView.dismiss();
}
```
