### ISSUE TITLE
Dismissable

### ISSUE THREAD

**Issue by Lonelabs** [Rogero0o/CatLoadingView#21]
By clicking on the screen, you can close the dialog.
Please add the ability to make the dialog not closable.

**Comment by alexanderbezverhni** [comment]
You can use the standard DialogFragment.setCancelable() method:

```
View catLoadingView = new CatLoadingView();
catLoadingView.setCancelable(false);
catLoadingView.show(getSupportFragmentManager(), "CatLoadingView");
```
