### ISSUE TITLE
onBakcPressed

### ISSUE THREAD

**Issue by KhuzaimaTariq** [Rogero0o/CatLoadingView#22]
how can i dismiss this dialogue onBackPressed( )  ?
i am using catLoadingView.setCancelable(false);
this is not working for me. Please guide me.

**Comment by Rogero0o** [comment]
fixed, you can use setCanceledOnTouchOutside(false)

**Comment by KhuzaimaTariq** [comment]
But this line is showing an error and its not editable
mView.setCanceledOnTouchOutside(false);

**Comment by Rogero0o** [comment]
Use new version
```
compile 'com.roger.catloadinglibrary:catloadinglibrary:1.0.4'
```

**Comment by KhuzaimaTariq** [comment]
can you please add OnCancleListner to this?

**Comment by Rogero0o** [comment]
You can use mView.getDialog().setOnCancelListener();
