### ISSUE TITLE
Force closed with error message: "java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState"

### ISSUE THREAD

**Issue by hendrawd** [Rogero0o/CatLoadingView#24]
### How to create the issue
- Create and show CatLoadingView
```kotlin
if (catLoadingView == null) {
    catLoadingView = CatLoadingView()
    catLoadingView?.isCancelable = false
}
catLoadingView?.show(supportFragmentManager, "")
```
- Dismiss CatLoadingView
```kotlin
catLoadingView?.dismiss()
```
- Start other activity with ```startActivityOnResult```
- Dismiss the new activity with ```RESULT_OK```
- Show CatLoadingView again with the first code inside ```onActivityResult``` of the first Activity

### What I have try to solve the problem
- Set the CatLoadingView to null after dismissed
```kotlin
catLoadingView = null
```
- Change the dismiss code with dismissAllowingStateLoss
```kotlin
catLoadingView?.dismissAllowingStateLoss()
```
- Override onSaveInstanceState based on https://stackoverflow.com/a/10261449/3940133
```kotlin
override fun onSaveInstanceState(outState: Bundle) {
    outState.putString("WORKAROUND_FOR_BUG_19917_KEY", "WORKAROUND_FOR_BUG_19917_VALUE")
    super.onSaveInstanceState(outState)
}
```
But didn't help
What working is wrapping the code with try catch that catch ```IllegalStateException``` but this workaround will make the ```CatLoadingView``` not showing  at all after showed for the first time.
### Stack trace
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
...
```

**Comment by Rogero0o** [comment]
I have tried but can't reproduce this bug.
Can you show me your code?

**Comment by hendrawd** [comment]
OK, I will make the test project and update here

**Comment by hendrawd** [comment]
Hi @Rogero0o , please try this project https://github.com/hendrawd/CatLoadingViewForceClosed and run the android test directly or by running manually and press back button in the `OtherActivity`

**Comment by Rogero0o** [comment]
Hi @hendrawd 
`    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == RC_SOMETHING && resultCode == Activity.RESULT_OK) {
            showData()
        }
    }`
Change `onActivityResult` like this then it works fine, please check it, thx.

**Comment by hendrawd** [comment]
So what I learn here, must call 
```kotlin 
super.onActivityResult(requestCode, resultCode, data)
``` 
first before doing anything in ```onActivityResult```
