### ISSUE TITLE
setBackgroundColor attribute not detected

### ISSUE THREAD

**Issue by phishiewow** [Rogero0o/CatLoadingView#29]
I wanna change background color of dialog but it doesnt detect setBackgroundColor attribute, what i need to do

mView.setBackgroundColor(Color.parseColor("#000000"));

**Comment by karthicbz** [comment]
Yes, Unable to set background color for the dialogue

**Comment by AllwinJohnson** [comment]
same happened for me

**Comment by gnanasreekar** [comment]
That is because import android.support.v4.app.DialogFragment;
is being used instead of import androidx.fragment.app.DialogFragment;
so the dialog components are not working

**Comment by Rogero0o** [comment]
Have update to androidx, please check
