### ISSUE TITLE
New Loading

### ISSUE THREAD

**Issue by tellfa** [Rogero0o/CatLoadingView#3]
Hi, thanks you for this library.
can you develop another LoadingView such as this image ?

http://mmbiz.qpic.cn/mmbiz/TTkedQ4uv7Khpcbibt7ibb143EWlHyQKxj0pkDibOXfib25BYWZeWFyetVH5GsxDvtelwicWA4HeqB1d9J3Kxlzia9iaw/0?wx_fmt=gif&tp=webp&wxfrom=5&wx_lazy=1

**Comment by Rogero0o** [comment]
I will try if i get time , but this one seems to be more difficult to develop.

**Comment by tellfa** [comment]
Yes this loading is difficult idea for develop, but it is very cool and nice! if you develop this loading please send link this issue. thanks a lot my dear friend

**Comment by Rogero0o** [comment]
Check this https://github.com/Rogero0o/GifLoadingView ， maybe you can find what you want .

**Comment by tellfa** [comment]
Thank you my dear friend :heart:
