### ISSUE TITLE
java.lang.IllegalStateException: Fragment already added: CatLoadingView

### ISSUE THREAD

**Issue by ezechuka** [Rogero0o/CatLoadingView#36]
When I use the CatLoadingView in my activity, it works fine. But when I kill the activity and come back the second time to use the CatLoadingView I get: java.lang.IllegalStateException: Fragment already added: CatLoadingView.

This is the method for display the CatLoadingView

` public void displayLoader(FragmentManager fm, boolean display) {
        if (view == null) {
            view = new CatLoadingView();
            view.setBackgroundColor(Color.parseColor("#88003CC0"));
            view.setText("Please wait");
        }

        if (display) {
            if (!view.isAdded())
                view.show(fm, TAG);
        } else if (!display && view.isVisible()){
            view.dismiss();
        }
}`

**Comment by Rogero0o** [comment]
The CatLoadingView is a DialogFragment, maybe you should check the states when Activity restored。
