### ISSUE TITLE
InflateException: Binary XML file 

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [Rogero0o/CatLoadingView#37]
InflateException: Binary XML file line #35: Error inflating class com.roger.catloadinglibrary.EyelidView

**Comment by wen-yuan-zhang** [comment]
I met the same question just now. Have you solved it? Thanks.

**Comment by ghost** [comment]
Same here D:

**Comment by Rogero0o** [comment]
Can you provide your device and the whole log for the crash? thx

**Comment by enginershakilahmed** [comment]
InflateException: Binary XML file line #35: Error inflating class com.roger.catloadinglibrary.EyelidView

**Comment by SenjuObito** [comment]
met same question. Has the developer solved it? Honor phone

**Comment by sunil-singh-chaudhary** [comment]
i have update this code pls check here https://github.com/sunil-singh-chaudhary/Cat-Loading-Dialog

**Comment by techxeeapps** [comment]
anybody who is still facing this issue add this to your app gradle
implementation "org.jetbrains.kotlin:kotlin-stdlib:1.4.10"

**Comment by Rogero0o** [comment]
I think @techxeeapps have resolve this issue
