### ISSUE TITLE
严重bug

### ISSUE THREAD

**Issue by zhaoxiuyu** [Rogero0o/CatLoadingView#7]
![screenshot_2016-05-25-13-31-57_com zxy administrator iwantindiana](https://cloud.githubusercontent.com/assets/16554580/15529133/6b4a313c-227d-11e6-964f-c6de8248af75.png)

眼睛上面的眉毛  太突出了，都跑到脸的外边去了，
下面的L O A D I N G ...文字只显示了 一半。

**Comment by Rogero0o** [comment]
抱歉，这个动画库只适配了 Nexus5 ，在别的分辨率或者模拟器上是有适配问题的，可以用我的另一个库 GifLoadingView 来显示这个动图，那样应该没有适配问题。
