### ISSUE TITLE
同一个页面，我如何让catloadingview再一次show出来

### ISSUE THREAD

**Issue by thefirstcoder** [Rogero0o/CatLoadingView#9]
你好，我现在遇到这样的问题：
当我从关闭另一个activity的时候得到onActivityResult的回调，这个时候再次调用catLoadingView的时候会崩溃，异常是not perform this action after onsavedInstanceState，意思是保存状态之后我不能再添加commit这个事务了，那么我应该如何再次show出catLoadView.

**Comment by Rogero0o** [comment]
可以参考这篇博文：http://blog.csdn.net/ranxiedao/article/details/8214936
